# Specify the version of docker-compose
version: '2' # It matches local version of our docker compose

services:
  backend:
    build: ./ # Rather than loading an image. We, are looking to build an image using our Docker File
    ports:
      - 8000:8000 # Mapped docker port 8000(left-side) to our local port 8000 (right-side)
      - 9229:9229 # Default debugger port
    volumes:
      - .:/usr/share/app # Mount the local src folder with our docker src to quick keep track of changes.
      - /usr/share/app/node_modules # Making sure only docker uses it own node modules and not shares with host machine.
    command: yarn start:docker
    depends_on: # This makes sure our postgres server is running before backened server
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
      PORT: 8000

  postgres:
    image: postgres:14-alpine # More optimized version of postgres
    ports:
      - 5432:5432 # To connect postgres locallly outside docker
    environment:
      POSTGRES_DB: webapp_dev # Change _dev to _prod to define a production database
      POSTGRES_HOST_AUTH_METHOD: trust
